<?php

namespace AppBundle\Repository;

/**
 * FoodItem
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodItem extends \Doctrine\ORM\EntityRepository
{
}
