<?php

namespace AppBundle\Repository;

/**
 * FoodBankListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodBankListRepository extends \Doctrine\ORM\EntityRepository
{
}
