<?php

namespace AppBundle\Repository;

/**
 * FoodItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodItemRepository extends \Doctrine\ORM\EntityRepository
{
}
