<?php

namespace AppBundle\Repository;

/**
 * FoodBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodBankRepository extends \Doctrine\ORM\EntityRepository
{
}
